#cat << EOF > ./<directory_name>/install-config.yaml
apiVersion: v1
baseDomain: dev.mindsparks.io
compute:
- architecture: amd64 
  hyperthreading: Enabled
  name: worker
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: testgb
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.0.0/16
  networkType: OVNKubernetes 
  serviceNetwork:
  - 172.30.0.0/16
platform: 
  vsphere:
    vCenter: 10.25.60.13
    username: administrator@vsphere.local
    password: vCenter!234
    datacenter: dc-iac-esx-devg-01
    defaultDatastore: dscl-iac-esx-devg-01
      apiVIPs:
        - 10.25.58.30
      ingressVIPs:
        - 10.25.58.30
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNzJhMzk3NmZlZmExNGM5MTkyYzM2YWQ3YTgxNGJmNWY6S081OEFKNjEwMTFZUTZMSkE1S0hMUk5NT1BBV0RHMkRBNUdOWjc1UTNKVVUzNDlaNllYSUVCVU83TUFJWDRPUQ==","email":"divyalakshmi.g@hpe.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNzJhMzk3NmZlZmExNGM5MTkyYzM2YWQ3YTgxNGJmNWY6S081OEFKNjEwMTFZUTZMSkE1S0hMUk5NT1BBV0RHMkRBNUdOWjc1UTNKVVUzNDlaNllYSUVCVU83TUFJWDRPUQ==","email":"divyalakshmi.g@hpe.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWE1MjZkOGIzLTU2ZDMtNDk5MC04ZDQyLTNkNzllMjk2YjFiOTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTRPV014Wm1VM1lXTTFZV00wWWpkaE9XSXdZbVk1T1ROaE1UWmxNRFE1TXlKOS5jYVVmQ3pVS09jdjBUc3R3SDljZEhMM0hqcDNsTHV1X1RQQ18wQ25KQXFlLWs0UnVaa04tSXZ6WHY2ZXp2allXcExyb1kzcHNsRUJQelR2eldaNXIzcE52R0s1OTFIOUprVjNISmRXakxNRWR2MjlacXhSNXVqZ0ZPSG9PNk1tZjBkS01wQUtNUmQyV1hOdEQydk9Cc3QzaE53X2dfWFIxLU15UjJydnF6U0lxM1dSVU5TdlE2ZmlPdmtydzZOTWtCYjlOWXZORnlOcnlQNEI0ai1ad2JhZ3JvaHNtemxIQUd5RktuX0VBRFdRZ21sclRId1RXX0JzU0tlS29uMDE5ZlhpdThEVVNEanRZbFR4WGIwVUt2eW9fejkwalc2Y1UtOWl4VFIzenZTSVlPSlBZOUQxRzRIc1RXRmdxSk84dzcyR0VRcXV5ZlN2X2N3MjM5NmtPNUF6SU1VTXljTzlBVmlDM1ZXNzJQYnVsVXFkb3k2SHUzLXNrU3B0N2YzcS1Ed29WSHNxcW9wTXdiWlZjeTdCWVJkQ2tXeGU2eDR1WTBUQklKelFONlNpZHltNWhFWWpwQmRrOEtsQkQwRGFYZ1NlUElqd0c0ck93WERaamFSYmNQc19PWG9tLUotUHFMN2lmVVFqVXNlQThpREo2NDJoclJNUVdPbl9jeUFYNkxSRzJaMkUtSUNFNWFLbXpxZTVDNUlqWjVFUDJsODFvZkxkLTlHUDBORTA2MFRyVFRCeHhwNTRkdlZlalJKcFk4UWw0SUxRZ1JHbHBrcm5hVWpHaU5hZGZPNy1ub0JPZ0hEQ1RkRTAzMi1MSHp0dzJvdnd4YzNiZUdsUUFmXzRFR3o1X0Vock5TSGZuaUY5cG9xY0tTRy1Md05vbGw4MlVUazBjTGxEM3ZPaw==","email":"divyalakshmi.g@hpe.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWE1MjZkOGIzLTU2ZDMtNDk5MC04ZDQyLTNkNzllMjk2YjFiOTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTRPV014Wm1VM1lXTTFZV00wWWpkaE9XSXdZbVk1T1ROaE1UWmxNRFE1TXlKOS5jYVVmQ3pVS09jdjBUc3R3SDljZEhMM0hqcDNsTHV1X1RQQ18wQ25KQXFlLWs0UnVaa04tSXZ6WHY2ZXp2allXcExyb1kzcHNsRUJQelR2eldaNXIzcE52R0s1OTFIOUprVjNISmRXakxNRWR2MjlacXhSNXVqZ0ZPSG9PNk1tZjBkS01wQUtNUmQyV1hOdEQydk9Cc3QzaE53X2dfWFIxLU15UjJydnF6U0lxM1dSVU5TdlE2ZmlPdmtydzZOTWtCYjlOWXZORnlOcnlQNEI0ai1ad2JhZ3JvaHNtemxIQUd5RktuX0VBRFdRZ21sclRId1RXX0JzU0tlS29uMDE5ZlhpdThEVVNEanRZbFR4WGIwVUt2eW9fejkwalc2Y1UtOWl4VFIzenZTSVlPSlBZOUQxRzRIc1RXRmdxSk84dzcyR0VRcXV5ZlN2X2N3MjM5NmtPNUF6SU1VTXljTzlBVmlDM1ZXNzJQYnVsVXFkb3k2SHUzLXNrU3B0N2YzcS1Ed29WSHNxcW9wTXdiWlZjeTdCWVJkQ2tXeGU2eDR1WTBUQklKelFONlNpZHltNWhFWWpwQmRrOEtsQkQwRGFYZ1NlUElqd0c0ck93WERaamFSYmNQc19PWG9tLUotUHFMN2lmVVFqVXNlQThpREo2NDJoclJNUVdPbl9jeUFYNkxSRzJaMkUtSUNFNWFLbXpxZTVDNUlqWjVFUDJsODFvZkxkLTlHUDBORTA2MFRyVFRCeHhwNTRkdlZlalJKcFk4UWw0SUxRZ1JHbHBrcm5hVWpHaU5hZGZPNy1ub0JPZ0hEQ1RkRTAzMi1MSHp0dzJvdnd4YzNiZUdsUUFmXzRFR3o1X0Vock5TSGZuaUY5cG9xY0tTRy1Md05vbGw4MlVUazBjTGxEM3ZPaw==","email":"divyalakshmi.g@hpe.com"}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3xR52S7bgMZk3J1wGUc1BXB0hoTnVZ5d5OVOe2hB7AnJwYADNL6eV1zI+gwyt4hfjWH5FNwCZhj3ZYzs7I9gfRVA0ey+zbE4CUf28IRBUMYRt7rkqKvb9HWNP1KZDy7xPQpoE0TiegUaNYjeVXo4sGddBCN2+pyJ9c/YxudJNAhBUCQtciBvp/OSNeEHJiwdBGMGF5TCJ5UAl2C+Qx+egKYXhPJC0x/s4IfaL5VR3c3P804rsdnqvzqK2uHF9xBGlz2hsadaKhkozugzq3M8ukt2VGVFhu1tiGtGYbdlXJxFbGQeuSogzSGGkTbzOk1LGUkYUzNao9yzMRhj1oR1MW7XRc9RkpCn4P0wae1cYPkEEcseRBJkUAuMG8p4Fpccucy9WJr06lLlZ69zueDaYEXBXvdjb7sQ4oHyjApYG47MvUH/qlIeze2svJuGw4rAU1slDp5iEhKebU6bAuM+uW8qGGzXKs/fgCfGKt6LTvWZZbCYnCfwszWMnC8RBne0= root@gccvmesxcncdvsvc' 